recipebook/recipebook/apps/recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('category/<slug:slug>/', views.category_detail, name='category_detail'),  # Страница категории
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('<int:recipe_id>/', views.detail, name = 'detail'),
    path('<int:recipe_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
    path('add/', views.add_recipe, name='add_recipe'),
    path('<int:recipe_id>/edit/', views.edit_recipe, name='edit_recipe'),
    path('<int:recipe_id>/delete/', views.delete_recipe, name='delete_recipe'),
]

recipebook/recipebook/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('recipe/', include('recipe.urls')),
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipebook/recipebook/apps/recipe/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.utils.timezone import now
import os
from django.utils.text import slugify
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         UserProfile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()
    
    
# class UserProfile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     name = models.CharField(max_length=50)
#     email = models.EmailField()
    
#     def __str__(self):
#         return f"{self.user.username} Profile"
    
    
class Category(models.Model):
    """Категория рецепта"""
    title = models.CharField(max_length=100, verbose_name='Категория', null=False, blank=False)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title   


def upload_recipe_photo(instance, filename):
    """
    Функция для автоматического создания директорий по пути,
    основанному на текущей дате, и сохранения изображения.
    """
    # Формируем путь к директории, основываясь на текущей дате
    folder_path = f"photos/{now().strftime('%Y/%m/%d')}"
    
    # Полный путь к файлу, включая имя файла
    full_path = os.path.join(settings.MEDIA_ROOT, folder_path, filename)
    
    # Проверяем, существует ли директория. Если нет, создаем её.
    directory = os.path.dirname(full_path)
    if not os.path.exists(directory):
        os.makedirs(directory)
    
    # Возвращаем сформированный путь для сохранения изображения
    return os.path.join(folder_path, filename)

class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe_title = models.CharField('Название рецепта', max_length = 200)
    recipe_foto = models.ImageField('Фото рецепта', upload_to=upload_recipe_photo, blank=True, null=True)
    recipe_ingredients = models.TextField('Ингридиенты рецепта')
    recipe_text = models.TextField('Описание рецепта')
    recipe_preparation = models.TextField('Шаги приготовления')
    recipe_time = models.TimeField('Время приготовления')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    category = models.ForeignKey(Category, verbose_name='Категория рецепта', on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.recipe_title
    
    def was_published_recent(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))
    
    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        

class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete = models.CASCADE)
    author_name = models.CharField('Имя автора', max_length = 50)
    author_text = models.CharField('Текст комментария', max_length = 200)
    
    def __str__(self) -> str:
        return self.author_name
    
    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        

recipebook/recipebook/apps/recipe/forms.py
from django import forms
from .models import Recipe, Category
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['recipe_title', 'recipe_foto', 'recipe_ingredients', 'recipe_text','recipe_preparation','category', 'recipe_time']
        widgets = {
            'recipe_ingredients': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ингредиенты', 'rows': 5}),
            'recipe_text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Описание', 'rows': 5}),
            'recipe_preparation': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Шаги приготовления', 'rows': 7}),
            'recipe_time': forms.TimeInput(attrs={'class': 'form-control', 'placeholder': 'Время приготовления'})
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.all()
        
    def save(self, commit=True):
        instance = super().save(commit=False)
        # Получаем текущее значение id рецепта
        recipe_id = instance.id
        # Изменяем имя файла, чтобы оно соответствовало id рецепта
        file = self.cleaned_data.get('recipe_foto')
        if file:
            filename = f'recipe_{recipe_id}.jpg'
            instance.recipe_foto.name = filename
        
        if commit:
            instance.save()
        return instance
        
class EditRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['recipe_title','recipe_foto','recipe_ingredients', 'recipe_text','recipe_preparation','recipe_time']
        widgets = {
            'recipe_ingredients': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ингредиенты', 'rows': 5}),
            'recipe_text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Описание', 'rows': 5}),
            'recipe_preparation': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Шаги приготовления', 'rows': 7})
        }
        
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

recipebook/recipebook/apps/recipe/views.py
import datetime
from django.http import Http404, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from .models import Recipe,Category #UserProfile
from django.contrib.auth.models import User
from .forms import RecipeForm, EditRecipeForm, SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# def index(request):
#     latest_recipes_list = Recipe.objects.order_by('-pub_date')[:10]
#     return render(request, 'recipe/book.html',{'latest_recipes_list': latest_recipes_list})
def index(request):
    # # Получаем все рецепты, отсортированные по дате публикации
    recipes_list = Recipe.objects.order_by('-pub_date')
    # Создаем объект Paginator с количеством объектов на одной странице
    paginator = Paginator(recipes_list, 10)
    # Получаем номер текущей страницы из GET-запроса
    page_number = request.GET.get('page', 1)
    try:
        # Извлекаем текущую страницу объектов
        page = paginator.page(page_number)
    except PageNotAnInteger:
        # Если страница не является числом, возвращаем первую страницу
        page = paginator.page(1)
    except EmptyPage:
        # Если запрашиваемая страница больше максимального числа страниц, возвращаем последнюю страницу результатов
        page = paginator.page(paginator.num_pages)
    categories = Category.objects.all()
    context = {
        'latest_recipes_list': page,
        'paginator': paginator,
        'categories': categories,
        }
    return render(request, 'recipe/book.html', context)


def detail(request, recipe_id):
    # try:
    #     r = Recipe.objects.get(id = recipe_id)
    # except:
    #     raise Http404("!Рецепт не найден!")
    recipe = get_object_or_404(Recipe, id = recipe_id)
    latest_comments_list = recipe.comment_set.order_by("-id")[:5]
    if request.user == recipe.author:
        auth_state = True
    else:
        auth_state = False
    context = {
        'recipes': recipe,
        'latest_comments_list':latest_comments_list,
        'auth_state': auth_state
    }
    return render(request,'recipe/detail.html', context)


def leave_comment(request, recipe_id):
    try:
        r = Recipe.objects.get(id = recipe_id)
    except:
        raise Http404("!Рецепт не найден!")
    r.comment_set.create(author_name = request.user, author_text = request.POST['text'])
    return HttpResponseRedirect(reverse('recipes:detail',args=(r.id,)))


@login_required
def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user            # Связываем автора рецепта с текущим пользователем
            # recipe.pub_date = datetime.datetime.now()
            recipe.save()
            messages.success(request, 'Рецепт успешно добавлен!')
            return HttpResponseRedirect(reverse_lazy('recipes:index'))
    else:
        form = RecipeForm()
    return render(request, 'recipe/add_recipe.html', {'form': form})


def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id = recipe_id)
    if recipe.author == request.user:
        if request.method == 'POST':
            return HttpResponseRedirect(reverse('recipes:detail',args=(recipe.id,)))
        else:
            form = EditRecipeForm(instance=recipe)
            return render(request, 'recipe/edit_recipe.html', {'recipe': recipe, 'form': form})
    else:
        return HttpResponseForbidden()

    
def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id = recipe_id)
    if recipe.author == request.user:
        if request.method == 'POST':
            # Удаляем рецепт
            recipe.delete()
            # Django автоматически удалит фотографию, связанную с рецептом
            return HttpResponseRedirect(reverse_lazy('recipes:index'))  # Переадресация на список рецептов
        return render(request, 'recipe/delete_recipe.html', {'recipe': recipe})
    else:
        return HttpResponseForbidden()
    
# Регистрация пользователя
class RegisterUser(CreateView):
    form_class = SignUpForm
    template_name = 'recipe/registration.html'
    success_url = reverse_lazy('recipes:index')

    def form_valid(self, form):
        valid = super(RegisterUser, self).form_valid(form)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return valid

# Авторизация пользователя
def check_if_user_exists(username):
    """
    Функция проверяет, существует ли пользователь с указанным именем.
    :param username: имя пользователя для проверки
    :return: True, если пользователь существует, False в противном случае
    """
    return User.objects.filter(username=username).exists()

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            password = form.cleaned_data.get('password')
            # Получаем имя пользователя из запроса
            username = request.POST.get('username', '')
            if check_if_user_exists(username):
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect(reverse_lazy('recipes:index'))
    else:
        form = AuthenticationForm()
    return render(request, 'recipe/login.html', {'form': form})

# Выход пользователя
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('recipes:index'))

def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    recipes = Recipe.objects.filter(category=category)
    # Создаем объект Paginator с количеством объектов на одной странице
    paginator = Paginator(recipes, 10)
    # Получаем номер текущей страницы из GET-запроса
    page_number = request.GET.get('page', 1)
    try:
        # Извлекаем текущую страницу объектов
        page = paginator.page(page_number)
    except PageNotAnInteger:
        # Если страница не является числом, возвращаем первую страницу
        page = paginator.page(1)
    except EmptyPage:
        # Если запрашиваемая страница больше максимального числа страниц, возвращаем последнюю страницу результатов
        page = paginator.page(paginator.num_pages)
    categories = Category.objects.all()
    
    context = {
        'category': category, 
        'recipes': recipes,
        'slug':slug,
        'latest_recipes_list': recipes,
        'paginator': paginator,
        'categories': categories,
        }
    return render(request, 'recipe/category_detail.html', context)

recipebook/recipebook/templates/recipe/add_recipe.html
{% extends 'base.html' %}

{% block title %}Добавить рецепт{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
        <h1>Добавить рецепт</h1>
    </div>
</div>

<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Добавить</button>
        <!-- Скрипт для удаления элементов с классом 'errorlist' -->
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                var errorLists = document.querySelectorAll('.errorlist');
                // Проходимся по всем найденным элементам с классом 'errorlist'
                errorLists.forEach(function(errorList) {
                    // Удаляем каждый элемент
                    errorList.remove();
                });
            });
        </script>
    </form>
</div>
{% endblock %}

recipebook/recipebook/templates/recipe/book.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
        <h1 class="display-4">Добро пожаловать на сайт рецептов!</h1>
        <p class="lead">Здесь вы найдете множество вкусных рецептов.</p>
        {% if request.user.is_authenticated %}
        <p class="lead">Пользователь: {{ request.user }}</p>
        {% endif %}
    </div>
</div>

<div class="container">
    <div class="row">
        {% if latest_recipes_list %}
            {% for recipe in latest_recipes_list %}
            <div class="col-sm-6 col-md-4">
                <div class="card mb-3">
                    <h5 class="card-title">{{ recipe.recipe_title }}</h5>
                    <img src="{{ recipe.recipe_foto.url }}" class="card-img-top" alt="{{ recipe.recipe_title }}">
                    <div class="card-body">
                        <hr>
                        <p  class="card-text">Описание: {{ recipe.recipe_text|truncatechars:50 }}</p>
                        <hr>
                        <p class="lead">Категория {{recipe.category}}</p>
                        <a href="{% url 'recipes:detail' recipe.id %}" class="btn btn-primary">Подробнее</a>
                        <em>Опубликовал {{recipe.author}}</em><br>
                    </div>
                </div>
            </div>
            {% endfor %}
        {%else%}
        <div class="col-sm-6 col-md-4">
            <div class="card mb-3">
                <p>В базе данных пока нет рецептов. Попробуйте добавить свой!</p>
                {% if request.user.is_authenticated %}
                    <form action="{% url 'recipes:add_recipe' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Добавить рецепт</button>
                    </form>
                {% else %}
                    <form action="{% url 'recipes:login_user' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Авторизация</button>
                    </form>
                {% endif %}                
            </div>
        </div>
        {% endif %}
    </div>
</div>

<!-- Блок с кнопками пагинации -->
<div class="pagination">
    <h1 class="lead">
        <strong>
    {% if recipes_page.has_previous %}
        <a href="{% url 'recipes:index' %}?page={{ recipes_page.previous_page_number }}">Предыдущая</a>
    {% endif %}
    
    {% for num in paginator.page_range %}
        {% if recipes_page.number == num %}
            <span class="current-page">{{ num }}</span>
        {% else %}
            <a href="{% url 'recipes:index' %}?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
    
    {% if recipes_page.has_next %}
        <a href="{% url 'recipes:index' %}?page={{ recipes_page.next_page_number }}">Следующая</a>
    {% endif %}
        </strong>
    </h1>
</div>
{% endblock %}

recipebook/recipebook/templates/recipe/category_detail.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Рецепты | {{ category.title }}</title>
</head>
<body>
<div class="container">
    <h1>Категория: {{ category.title }}</h1>
    {% include 'recipe/book.html' with recipes=recipes %}
</div>
</body>
</html>

recipebook/recipebook/templates/recipe/delete_recipe.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container text-center">
            <p class="lead"> <h1>Вы уверены, что хотите удалить этот рецепт?</h1></p>
            <hr>
            <p><form method="POST">  
                {% csrf_token %} 
                <a href="{% url 'recipes:detail' recipe.id%}" class="btn btn-secondary">Отмена</a>
                <button type="submit" class="btn btn-danger">Удалить</button>
            </form></p> 
        </div>
    </div>

{% endblock %}

recipebook/recipebook/templates/recipe/detail.html
{% extends 'base.html' %}

{% block title %} {{recipes.recipe_title}} {% endblock  %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container text-center">
            <h5 class="display-4">Название рецепта: {{recipes.recipe_title}}</h5>
            <p class="lead">Категория {{recipes.category}}</p>
        </div>
    </div>
    <img src="{{ recipes.recipe_foto.url }}" class="card-img-top" alt="{{ recipes.recipe_title }}">
    <hr>
    <p><strong>Ингридиенты рецепта:</strong> {{recipes.recipe_ingredients}}</p>
    <p><strong>Описание рецепта:</strong> {{recipes.recipe_text}}</p>
    <p><strong>Шаги приготовления:</strong> {{recipes.recipe_preparation}}</p>
    <em>Время приготовления: {{recipes.recipe_time}}</em><br>
    <em>Дата публикации {{recipes.pub_date}}</em><br>
    <em>Опубликовал автор {{recipes.author}}</em><br>

    {%if recipes.was_published_recent%}
    <em>Состояние - Новый рецепт</em><br>
    {%endif%}
    <hr>
    <p>
        <strong>
            Комментарии:
        </strong>
    </p>
    <hr>
        {% if latest_comments_list %}
            {% for c in latest_comments_list%}
            <p>
                Автор 
                <strong>
                    {{c.author_name}}
                </strong>
                <p>
                    {{c.author_text}}
                </p>
            </p>
            {%endfor%}
        {% else %}
            Комментарии не найдены
        {% endif %}
    <hr>
    {% if request.user.is_authenticated %}
    <form action="{% url 'recipes:leave_comment' recipes.id %}" method="POST"> 
        {% csrf_token %}
        {% comment %} <input type="text" required="" placeholder="Ваше имя" name="name"><br> {% endcomment %}
        <textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"> </textarea><br>
        <button type="submit"> Оставить комментарий
        </button>
    </form>
    {%else%}
        <em>Чтобы оставить комментарий, авторизуйтесь</em>
        <hr>
    {%endif%}
    {% if auth_state %}
        <a href="{% url 'recipes:edit_recipe' recipes.id %}" class="btn btn-primary">Изменить рецепт</a>
    {% endif %}
        <a href="{% url 'recipes:index' %}" class="btn btn-secondary">На главную</a>
    {% if auth_state %}
        <a href="{% url 'recipes:delete_recipe' recipes.id %}" class="btn btn-danger">Удалить рецепт</a>
    {% endif %}
{% endblock  %}

recipebook/recipebook/templates/recipe/edit_recipe.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
    <a href="{% url 'recipes:detail' recipe.id %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

recipebook/recipebook/templates/recipe/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Вход</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Войти</button>
</form>
{% endblock %}

recipebook/recipebook/templates/recipe/registration.html
{% extends 'base.html' %}

{% block content %}
<h1>Регистрация</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Зарегистрироваться">
</form>

<p>Уже есть аккаунт? <a href="{% url 'recipes:login_user' %}">Войдите</a></p>

{% endblock %}